apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: create-secrets-composer-ai
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: create-secrets-composer-ai
    spec:
      containers:
        - name: create-secrets-redsaia
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              oc wait --for jsonpath='{.status.phase}'=Active ns/composer-ai-gitops
              echo "Read the secret for RH composer ai"
              HF_TOKEN_ACCESS="$(oc extract secret/rh-composer-ai -n openshift-gitops --keys composer-ai-apps-ai-keys-huggingface_apikey --to=-)"
              echo "Create the composer-ai secret in Composer AI GitOps project"
              oc delete secret rh-composer-ai -n composer-ai-gitops --ignore-not-found
              oc create secret generic rh-composer-ai -n composer-ai-gitops --from-literal composer-ai-apps-ai-keys-huggingface_apikey="$HF_TOKEN_ACCESS"
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
