apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
  name: granite-3.0-8b-instruct
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/redhat-ai-services/modelcar-catalog:granite-3.0-8b-instruct
      generation: 2
      importPolicy:
        importMode: PreserveOriginal
        scheduled: true
      referencePolicy:
        type: Source
